name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Jdk 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: ./gradlew zipDist
      - name: Build Bundled
        run: ./gradlew zipBundledDist
      - name: Delete snapshot tag
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          git push --delete origin Snapshot
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/distributions/*.zip"
          allowUpdates: ${{ github.ref == 'refs/heads/main' }}
          tag: ${{ github.ref == 'refs/heads/main' && 'Snapshot' || '' }}
          commit: ${{ github.sha }}
          prerelease: ${{ github.ref == 'refs/heads/main' }}